version: 1

update_configs:
  - package_manager: python
    directory: /
    update_schedule: live
    default_reviewers:
      - umglurf
    allowed_updates:
      - match:
          update_type: "security"

  - package_manager: docker
    directory: /
    update_schedule: daily
    default_reviewers:
      - umglurf
    allowed_updates:
      - match:
          update_type: "security"
