name: Docker build and push

env:
  DOCKER_REGISTRY: docker.pkg.github.com
  DOCKER_REPO: umglurf/juleol
  DOCKER_IMAGE: juleol
  DOCKER_TAG: latest

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker build and push
      uses: docker/build-push-action@v1
      with:
        tags: ${{ env.DOCKER_TAG }}
        username: umglurf
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ${{ env.DOCKER_REGISTRY }}
